/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppAuth: typeof import("./src/components/AppAuth.vue")["default"]
    AppHeader: typeof import("./src/components/layout/AppHeader.vue")["default"]
    AppRegistration: typeof import("./src/components/AppRegistration.vue")["default"]
    AppSidebar: typeof import("./src/components/layout/AppSidebar.vue")["default"]
    ElAside: typeof import("element-plus/es")["ElAside"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElContainer: typeof import("element-plus/es")["ElContainer"]
    ElDropdown: typeof import("element-plus/es")["ElDropdown"]
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"]
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElMain: typeof import("element-plus/es")["ElMain"]
    ElMenu: typeof import("element-plus/es")["ElMenu"]
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
    ElPagination: typeof import("element-plus/es")["ElPagination"]
    ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"]
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
    ElTable: typeof import("element-plus/es")["ElTable"]
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"]
    ElTimeline: typeof import("element-plus/es")["ElTimeline"]
    ElTimelineItem: typeof import("element-plus/es")["ElTimelineItem"]
    IconITTP: typeof import("./src/components/icons/IconITTP.vue")["default"]
    ModalUserEdit: typeof import("./src/components/ModalUserEdit.vue")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    TableActions: typeof import("./src/components/TableActions.vue")["default"]
    TablePagination: typeof import("./src/components/TablePagination.vue")["default"]
    UserMenu: typeof import("./src/components/UserMenu.vue")["default"]
    UsersListTable: typeof import("./src/components/UsersListTable.vue")["default"]
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"]
  }
}
